language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: j/cErEl0nzkP2vLstZfTj7beP7yKSDag+SNR/4Oz3qNO/LvANcy4Lr7AzkaWu0laV9Mk+f9Mv5UIY/8EKpk0eW0mJuB6gMK/35gn9S1kDPodJ4pQSyu3gr58TfCnE/YaZ+z3aK/JiQrP2mfuRbkMy+N/TkDy8TICYmC+flx06UgXifEku0/PNTWcC5f1Vn+2N1AmOhCqck9rHewvXUGwWvMZp7w5zEqRNd42F4RoLcMgINIlWNciRTLvoK3jpX4c3MTclXLtwX8ZgdBPIWD58JlpzvjdK+7V73QrHUc0UaZHz7g1iBqXBGHOVOC22PpJQhtBIr5GEqT4bcdLj+2bzwCIgRJ4UFSRVjOlL2L8fmoTJMt+mLWn9LfhOpOHitttOF8is1M54gUmOaKR8mz+MfmduVBbmCAaTKKWq9Ft4Dg9r2dGuM/vyhTPVV7zYg/T2/9yDRyL7vDlLVqE0ZonNauy7KMwTLIPjKBlS3zY7Q5qe7Si/jm/lBkAeyGmwyoY1MEb4dcLh219WT9nJrlqa6CYZ98R3j3ZSs4rDdsNefPGAONlIC6xsTn6/qBu+mqO//J9Zu+U8XbtxRdXlmN9v7IVIE+7bDYnEwineMY5msKPmM954QkShuSjZLS4FGowBENbZ4Lzfzyh4IYYcmZ0Jk2y/wyQQgTNNEKKMMuBBuo=
  app: shrouded-basin-90892
  on:
    repo: dhoel/blogpost-testing
